### ISSUE TITLE
Not able to access sharepoint csv file

### ISSUE THREAD

**Issue by Dhyanesh97** [grafana/grafana-csv-datasource#136] opened 2021-11-10 08:21 UTC
**Describe the bug**
I configured link for a sharepoint csv and provided userName password by enabling Basic Auth and Skip TLS verify.
When i click on "Save & Test" it shows "database updated" and "success" message.

![image](https://user-images.githubusercontent.com/89400147/141075436-6c627e59-575c-44b0-b22b-dede9855a4cf.png)

But when i click on explore and provide column name, it shows error.
When i used my credentials of sharepoint it shows 403 forbidden error.

![image](https://user-images.githubusercontent.com/89400147/141074908-a19c3fbe-7527-43eb-aa72-d5b4724df2c8.png)

When i share that sharepoint file with someone and used their credentials it shows below error. (When i click on Save and Test it shows success message)

![image](https://user-images.githubusercontent.com/89400147/141075871-475e7407-50a0-4371-88fa-df064a8d6bb3.png)

**Version Details:**

- Grafana version : 8.2.1
- Plugin version : 0.6.1

**Additional context**

**Comment by marcusolsson** [comment] 2021-12-17 14:00
Looks like there might be some issues with the CSV data. Specifically, it looks like the columns don't match up. Could you maybe share some (anonymized) CSV data that reproduced the issue?

**Comment by marcusolsson** [comment] 2022-03-09 14:53
The health check doesn't check that the CSV data is valid, but only that you can access it.

**Comment by Dhyanesh97** [comment] 2022-03-09 15:39
![image](https://user-images.githubusercontent.com/89400147/157475177-aac4a434-e5cb-4eec-aff9-3e8bf11476f0.png)

Please find above image of csv file on SharePoint.

**Comment by marcusolsson** [comment] 2022-03-09 15:52
The URL needs to return raw CSV data. Could you confirm that the URL you've configured in the data source returns raw CSV data and not some SharePoint-specific format?

**Comment by Dhyanesh97** [comment] 2022-03-10 04:42
It wasn't raw csv data. So we moved to GitHub gist file where the data source was returning raw csv data.
Can you consider this as feature request ? If data is not in the raw format then plugin should convert it and then display.

**Comment by marcusolsson** [comment] 2022-03-10 10:59
Sounds like it would be outside of the scope of this plugin, since it wouldn't be CSV anymore. Similarly to the [Google Sheets](https://grafana.com/grafana/plugins/grafana-googlesheets-datasource/) data source, I think it would be its own plugin. Closing this as it's not a bug.

**Closed as completed by marcusolsson** 2022-03-10 10:59 UTC
