### ISSUE TITLE
disabled error

### ISSUE THREAD

**Issue by maxpy** [grafana/grafana-csv-datasource#300] opened 2024-03-08 10:32 UTC
![image](https://github.com/grafana/grafana-csv-datasource/assets/261672/45c7f2f3-a422-4eb4-8581-fde359bec20f)

**Comment by zoltanbedi** [comment] 2024-03-11 14:20
@maxpy which grafana version are you using? which os?

**Comment by maxpy** [comment] 2024-03-20 07:30
Grafana v10.2.2 (161e3cac5075540918e3a39004f2364ad104d5bb)
Running Grafana in docker container

**Comment by gabor** [comment] 2024-05-23 14:45
hi @maxpy , unfortunately i am unable to reproduce this. i tried running grafnaa `v10.2.2` in docker, and install the current csv-plugin-version (`0.6.18`), and it worked correctly.

could you please try this with the newest plugin-version (`0.6.18` right now)?

**Comment by gabor** [comment] 2024-06-21 08:27
as we got no new information, we're closing the issue. we can reopen it if we get new info.

**Closed as completed by gabor** 2024-06-21 08:27 UTC
