### ISSUE TITLE
Time range is ignored for some visualizations (barchart, piechart)

### ISSUE THREAD

**Issue by nils-trubkin** [grafana/grafana-csv-datasource#240] opened 2023-07-03 19:02 UTC
When using a CSV data source, visualizations such as bar charts and piechart completely ignore time ranges (last 5 minutes, last hour, last month, etc.)

Some other visualizations work as expected, mainly time series and similar graphs, as the timeline, is just being zoomed in and out to limit the requested time range. Data itself is still "whole"; it's not being transformed or filtered.

It is impossible to query CSV by date in a sense. Is that the correct and expected "feature," or is this a bug?

**Comment by zoltanbedi** [comment] 2023-10-09 21:21
duplicate of #231

**Closed as completed by zoltanbedi** 2023-10-09 21:21 UTC
