### ISSUE TITLE
CSV plugin picking unknown remote_addr and throwing 500 Internal server error

### ISSUE THREAD

**Issue by sravanthnag** [grafana/grafana-csv-datasource#205] opened 2022-07-08 05:34 UTC
Hi,

The csv plugin was working fine until sometime back. Since starting this week, the plugin is throwing strange error.
There has been no change in grafana version or the plugin version since many weeks. 

Query data error
Object
status:500
statusText:"Internal Server Error"
data:Object
message:"Query data error"
traceID:"00000000000000000000000000000000"
config:Object
url:"api/ds/query"
method:"POST"
data:Object
requestId:"Q1541"
retry:0
headers:Object
hideFromInspector:false
message:"Query data error"

In grafana logs, i can see below entries. The remote_addr it refers here is entirely different IP. I am using a local csv read option but this IP is not my local machine IP. What and where is it fetching this IP from ? Any clue or pointers ?

a: Failed to query data: rpc error: code = Unavailable desc = error reading from server: EOF" remote_addr=XX.XX.XX.XXX traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-07-08T05:01:21.39+0000 lvl=eror msg="Request Completed" method=POST path=/api/ds/query status=500 remote_addr=XX.XX.XX.XXX time_ms=6 duration=6.192578ms size=75 referer="[http://XX.XX.YY.YYY:3000/d/X8CXJ0Xnz/dashboard?orgId=1&from=now-30m&to=now"](http://XX.XX.YY.YYY:3000/d/X8CXJ0Xnz/dashboard?orgId=1&from=now-30m&to=now%22) traceID=00000000000000000000000000000000

Workaround which works for temporary moment is :
- Edit Panel, do any minor modification to properties and undo changes, graph will be visible.
- Apply changes in panel, graph is still visible
- But as soon as you change time or click refresh on top of grafana right corner, all graphs are lost and same error repeats.

PS : I am loading 10-20 CSV files from a fixed backend location to plot different graphs. As i said, this was working flawlessly till sometime back. Not exactly sure what happened but these are errors I have noticed.

Primarily I suspect the remote_addr. How is the remote_addr fetched inside the plugin code ?

**Comment by vineetraja** [comment] 2023-05-04 11:26
From my setup I can infer that the `remote_addr` is the IP of the client on which one is viewing grafana.

Having said that I am too facing these random "Internal Server Error 500"
In my use case, the csv file is very small (143 kb), and there seems to be no co-relation with response times either.

Although it works with few manual refreshes, but this is not production grade. I would not like my users to be confused at random.

**Comment by borjasueiro** [comment] 2023-06-08 11:31
Would it be possible for the request to be made from the grafana server instead of from user browser?

**Comment by zoltanbedi** [comment] 2023-10-09 20:48
Which grafana version are you experiencing this?

**Comment by zoltanbedi** [comment] 2023-11-27 14:29
This is a duplicate of #214

**Closed as completed by zoltanbedi** 2023-11-27 14:29 UTC
